# -*- coding: utf-8 -*-
import re
import string

VERBS = ["reconoció","comentó","habló","manifestó", "declaró","expresó","expuso","dijo","dio detalles","apuntó"
        "mencionó","formuló","anunció","enunció","enumeró","observó", "refirió", "anticipó", "cruzó",
        "contó","opinó","propuso","aseveró","sostuvo","afirmó","criticó","estalló", "confirmó","resaltó"]

ENTITIES = [
    "Abel Albino",                
    "Adolfo Rodríguez Saá",              
    "Adrián Paenza",              
    "Agustín Rossi",              
    "Alberto Fernández",              
    "Alberto Pérez",              
    "Alberto Rodríguez Saá",              
    "Alberto Sileoni",              
    "Alcira Argumedo",              
    "Alejandra Gils Carbó",              
    "Alejandro Arlía",              
    "Alejandro Tullio",              
    "Alfonso Prat Gay",              
    "Alfredo Scoccimarro",              
    "Alicia Kirchner",              
    "Alieto Guadagni",              
    "Amado Boudou",              
    "Ana María Edwin",              
    "Ángela Merkel",              
    "Aníbal Fernández",              
    "Antonio Bonfatti",              
    "Artemio López",              
    "Arturo Puricelli",              
    "Augusto Costa",              
    "Axel Kicillof",              
    "Barack Obama",              
    "Beatriz Sarlo",              
    "Carlos Heller",              
    "Carlos Kunkel",              
    "Carlos Menem",              
    "Carlos Pagni",              
    "Carlos Reutemann",              
    "Carlos Tomada",              
    "César Milani",              
    "Claudio Belocopitt",              
    "Claudio Lozano",              
    "Cristian Ritondo",              
    "Cristina Fernández de Kirchner",              
    "Cristóbal López",              
    "Daniel Filmus",              
    "Daniel Hadad",              
    "Daniel Peralta",              
    "Daniel Reposo",              
    "Daniel Scioli",              
    "Danilo Astori",              
    "Darío Giustozzi",              
    "David Cameron",              
    "Débora Giorgi",              
    "Diego Bossio",              
    "Diego Santilli",              
    "Dilma Rousseff",              
    "Domingo Cavallo",              
    "Eduardo Amadeo",              
    "Eduardo Costantini",              
    "Eduardo Duhalde",              
    "Elisa Carrió",              
    "Enrique Peña Nieto",              
    "Ernesto Sanz",              
    "Esteban Bullrich",              
    "Esteban Righi",              
    "Eugenio Zaffaroni",              
    "Facundo Moyano",              
    "Federico Pinedo",              
    "Federico Sturzenegger",              
    "Felipe Rodríguez Laguens",              
    "Felipe Solá",              
    "Félix Díaz",              
    "Fernando de la Rúa",              
    "Fernando Iglesias",              
    "Fernando Navarro",              
    "Fernando Solanas",              
    "Florencia Saintout",              
    "Florencio Randazzo",              
    "Francisco de Narváez",              
    "Franco Macri",              
    "Gabriel Mariotto",              
    "Gabriela Cerruti",              
    "Gabriela Michetti",              
    "Gerónimo Venegas",              
    "Gerry Garbulsky",              
    "Gilberto Alegre",              
    "Gildo Insfrán",              
    "Guillermo Montenegro",              
    "Guillermo Pereyra",              
    "Gustavo Béliz",              
    "Héctor Recalde",              
    "Héctor Timerman",              
    "Hermes Binner",              
    "Hernán Lombardi",              
    "Horacio Rodríguez Larreta",              
    "Horacio Verbitsky",              
    "Hugo Biolcati",              
    "Hugo Chávez",              
    "Hugo Moyano",              
    "Hugo Yasky",              
    "Ider Peretti",              
    "Iván Petrella",              
    "Javier González Fraga",              
    "Jorge Altamira",              
    "Jorge Argüello",              
    "Jorge Bergoglio",              
    "Jorge Capitanich",              
    "Jorge Di Lello",              
    "Jorge Lanata",              
    "Jorge Lemus",              
    "Jorge Macri",              
    "Jorge Sapag",              
    "Jorge Taiana",              
    "José Alperovich",              
    "José Ignacio de Mendiguren",              
    "José Manuel de la Sota",              
    "José María Campagnoli",              
    "José Sbatella",              
    "Joseph Goebbels",              
    "Juan Cabandié",              
    "Juan Carr",              
    "Juan José Aranguren",              
    "Juan José Campanella",              
    "Juan José Llach",              
    "Juan José Mussi",              
    "Juan Manuel Abal Medina",              
    "Juan Manuel Urtubey",              
    "Juan Pablo Schiavi",              
    "Julián Dindart",              
    "Julián Domínguez",              
    "Juliana Di Tullio",              
    "Julio Alak",              
    "Julio Cobos",              
    "Julio De Vido",              
    "Julio Pereyra",              
    "Julio Piumato",              
    "León Arslanián",              
    "Luis D Elía",              
    "Luis Juez",              
    "Luis Majul",              
    "Luis Miguel Etchevehere",              
    "Luis Naidenoff",              
    "Luis Zamora",              
    "Lula da Silva",              
    "Marcelo Rubinstein",              
    "Marcelo Stubrin",              
    "Marcelo Tinelli",              
    "Marcos Aguinis",              
    "Margarita Stolbizer",              
    "María Eugenia Estenssoro",              
    "María Eugenia Vidal",              
    "Mariano Grondona",              
    "Mariano Rajoy",              
    "Mariano Recalde",              
    "Mario Das Neves",              
    "Mario Ishii",              
    "Mario Pergolini",              
    "Martín Caparrós",              
    "Martín Insaurralde",              
    "Martín Lousteau",              
    "Martín Redrado",              
    "Martín Sabbatella",              
    "Maurice Closs",              
    "Mauricio Macri",              
    "Mempo Giardinelli",              
    "Mercedes Marcó del Pont",              
    "Miguel Del Sel",              
    "Miguel Galuccio",              
    "Miguel Pesce",              
    "Miguel Pichetto",              
    "Nelson Castro",              
    "Néstor Kirchner",              
    "Nicolás Sarkozy",              
    "Nilda Garré",              
    "Nora De Lucía",              
    "Norberto Yauhar",              
    "Oscar Aguad",              
    "Oscar Parrilli",              
    "Pablo Javkin",              
    "Pablo Micheli",              
    "Rafael Bielsa",              
    "Rafael Di Zeo",              
    "Ricardo Alfonsín",              
    "Ricardo Casal",              
    "Ricardo Colombi",              
    "Ricardo Darín",              
    "Ricardo Echegaray",              
    "Ricardo Jaime",              
    "Ricardo Lorenzetti",              
    "Ricardo Pignanelli",              
    "Roberto Baradel",              
    "Roberto Feletti",              
    "Roberto Lavagna",              
    "Roberto Pianelli",              
    "Rogelio Frigerio",              
    "Rubén Giustiniani",              
    "Rubén Sobrero",              
    "Sergio Bergman",              
    "Sergio Berni",              
    "Sergio Massa",              
    "Sergio Urribarri",              
    "Silvia Majdalani",              
    "Silvina Batakis",              
    "Sonia Escudero",              
    "Víctor de Gennaro",              
    "Víctor Hugo Morales",              
    "Victoria Donda",              
    "Vilma Ibarra",              
    "Jorge Mayoral",              
    "Daniel Rafecas",              
    "Daniel Gollán",              
    "Julián Ercolini",              
    "Miguel Bein",              
    "Jaime Durán Barba",              
    "Roberto Carlés",              
    "Héctor Méndez",              
    "Germán Moldes",              
    "Ricardo Wechsler",              
    "Javier De Luca",              
    "Miguel Lifschitz",              
    "Pablo Ferreyra",              
    "María José Lubertino",              
    "Marcelo Ramal",              
    "Fernando Sánchez",              
    "Carlos Fayt",              
    "Mariana Gras",              
    "Fernando Niembro",              
    "Malena Galmarini",              
    "Rosendo Fraga",              
    "Luis Novaresio",              
    "Fernando Espinoza",              
    "Omar Perotti",              
    "Sergio Spolszki",              
    "Carlos Zannini",              
    "Luis María Cabral",              
    "Roberto Navarro",              
    "Myriam Bregman",              
    "Gerardo Milman",              
    "Claudio Bonadío",              
    "Sergio Szpolski",              
    "Fidel Castro",              
    "Mónica Busetti",              
    "Manuela Castañeira",              
    "Jaime Linares",              
    "Patricia Bullrich",              
    "José Cano",              
    "Eduardo Freiler",              
    "Patricia Giménez",              
    "Laura Alonso",              
    "Adelmo Gabbi",              
    "Juan Manzur",              
    "Carlos Melconian",              
    "Alejandro Granados",              
    "Nicolás Del Caño",              
    "Néstor Pitrola",              
    "Alberto Lugones",              
    "Omar Príncipe",              
    "Gerardo Morales",              
    "Juan Carlos Gemignani",              
    "Raúl Othacehé",              
    "Gustavo Menéndez",              
    "Marcelo Bonelli",              
    "Lino Barañao",              
    "Eugenio Burzaco",              
    "Guillermo Dietrich",              
    "Milagro Sala",              
    "Nicolás Caputo",              
    "Isela Costantini",              
    "Horacio Rosatti",              
    "Marcos Peña",              
    "Fernando Marín",              
    "Leonardo Nardini",              
    "Walter Festa",              
    "Julio Zamora",              
    "Martiniano Molina",              
    "Diego Valenzuela",              
    "Alberto Descalzo",              
    "Fernando Gray",              
    "Néstor Grindetti",              
    "Joaquín De la Torre",              
    "Verónica Magario",              
    "Ramiro Tagliaferro",              
    "Mariano Cascallares",              
    "Jorge Ferraresi",              
    "Patricio Mussi",              
    "Gabriel Katopodis",              
    "Juan Zabaleta",              
    "Luis Andreotti",              
    "Gustavo Posse",              
    "Emilio Basavilbaso",              
    "Graciela Camaño",              
    "Lucas Ghi",              
    "Gustavo Arribas",              
    "Omar Viviani"
    "Sebastián Casanello",              
    "Carlos Regazzoni",              
    "Graciela Ocaña",              
    "Leonardo Fariña",              
    "Susana Malcorra",              
    "Cecilia Pando",              
    "Pablo Avelluto",              
    "Nicolás Massot",              
    "Carlos Rosenkrantz",                       
    "José López",              
    "Donald Trump",              
    "Ibar Pérez Corradi",              
    "Felipe Miguel",              
    "Mario Quintana",              
    "Aldo Rico",              
    "Germán Garavano",              
    "Adrián Werthein",              
    "Guillermo Moreno",              
    "Fabiana Tuñez",              
    "Ricardo Buryaile",              
    "Héctor Daer",              
    "Carlos Acuña",              
    "Juan Carlos Schmid",              
    "Joaquín Morales Solá",              
    "Hebe de Bonafini",              
    "Michel Temer",              
    "Beatriz Busaniche",              
    "Pablo Moyano",              
    "Alejandro Nicola",              
    "Alejandro Amor",              
    "Héctor Polino",              
    "Noemí Ruiz",              
    "Sandra Maiorano",              
    "Pablo Tonelli",              
    "Hillary Clinton",              
    "Sonia Alesso",              
    "Juan Manuel Santos",              
    "Carolina Stanley",              
    "Raúl Alfonsín",              
    "Martín Ocampo",              
    "Sebastián Galmarini",
    "Máxima Zorreguieta",
    "Marcelo Orfila",
    "Eduardo De Pedro",
    "Fernando De Andreis",
    "Pablo López",
    "Marco Lavagna",
    "Lázaro Báez",
    "Javier Iguacel",   
    "Eduardo Costa",   
    "Teresa Luna",   
    "Matías Pellegrini",   
    "Leonardo Gasparini",   
    "Jorge Paz",   
    "Eduardo Chávez Molina",   
    "Gerardo Martínez",   
    "Luciano Laspina",   
    "Papa Francisco",   
    "Natalia Volosin",   
    "Alejandro Ceccatto",   
    "Alberto Abad",   
    "Daniel Lipovetzky",   
    "Emilio Monzó",   
    "Ana María Figueroa",   
    "Mariano Borinsky",   
    "Sebastián Galiani",   
    "Santiago Cantón",   
    "Mercedes Marcó",   
    "Joseph Lewis",         
    "Joe Lewis",         
    "Nicolás Dujovne",         
    "Ginés González García",         
    "Juan José Gómez Centurión",         
    "Daniel Angelici",         
    "Luis Alberto Scervino",         
    "Francisco Cabrera",         
    "Guillermo Raúl Jenefes",         
    "Jorge Triaca",         
    "Miguel Braun",         
    "Gabriela Boquín",         
    "María Cecilia Loccisano",         
    "Juan Carlos Maqueda",         
    "Nicolás Maduro",         
    "Amadeo Nicora",         
    "María Servini de Cubría",         
    "Romina Del Plá",         
    "Alejandro Cacetta",         
    "José Potocar",         
    "Santiago del Moro",         
    "Alejandro Fantino",         
    "Alfredo Leuco",         
    "Mariana Fabbiani",         
    "Maximiliano Montenegro",         
    "Emmanuel Macron",         
    "Marine Le Pen",         
    "Shinzo Abe",         
    "Xi Jinping",         
    "Antonio Caló",         
    "Mariana Zuvic",         
    "Juan Schiaretti",         
    "Jorge Videla",         
    "José Martínez de Hoz",         
    "Juan Manuel Culotta",         
    "Máximo Kirchner",         
    "Alberto Roberti",         
    "Rodrigo Rodríguez",         
    "Andrés Guzmán",         
    "Enrique Senestrari",         
    "Reinaldo Rodríguez",        
    "Fernanda Vallejos",         
    "Lucía Galán",         
    "Santiago Corcuera",         
    "Alberto Dalla Vía",         
    "Matías Tombolini",         
    "Santiago Maldonado",         
    "Héctor Baldassi",         
    "Martín Llaryora",         
    "Guido Otranto",         
    "Julio López",         
    "Gustavo Lleral",         
    "Pablo Carro",         
    "Silvina Ávila",         
    "Cristiano Rattazzi",         
    "Ariel Lijo",         
    "Alejandro Burzaco",         
    "Santiago Nardelli",         
    "Rosío Antinori",         
    "Miguel Etchecolatz",         
    "Omar Suárez",         
    "Andrés Ibarra",         
    "Martín Casares",         
    "Javier Ibáñez",         
    "Adolfo Rubinstein",         
    "Inés Weinberg de Roca",         
    "Luis Caputo",         
    "Eduardo Farah",         
    "Jorge Ballestero",         
    "Christine Lagarde",         
    "Alfredo Cornejo",         
    "Kim Jong-un",         
    "Florencia Peña",         
    "Juliana Awada",         
    "Marcelo Fuentes",         
    "Andrés Manuel López Obrador",         
    "Marcela Campagnoli",         
    "Alejandro Finocchiaro",         
    "Darío Lopérfido",         
    "Gabriel Sánchez Zinny",         
    "Ana Claudia Almirón",         
    "Gladys González",         
    "Humberto Schiavoni",         
    "Mirta Tundis",         
    "Jaim Bolsonaro",         
    "Leopoldo Bruglia",         
    "Pablo Bertuzzi",         
    "Lenín Moreno",         
    "Martín Vizcarra",         
    "Pedro Pablo Kuczynski",         
    "Jimmy Morales",         
    "Fernando Haddad",         
    "Jair Bolsonaro",         
    "Liliana Catucci",         
    "Carlos Mahíques",         
    "Eduardo Riggi",         
    "Vladimir Putin",         
    "Magdalena Odarda",         
    "Eugenio Cozzi",         
    "Soledad Acuña",         
    "Ismael Bermúdez",         
    "Luis Rodríguez",         
    "Carlos Stornelli",         
    "Omar Gutiérrez",         
    "Alejo Ramos Padilla",         
    "Samuel Gelblung",         
    "Sergio Uñac",         
    "Dante Sica",         
    "Nancy Duplaa",         
    "Dolores Fonzi",         
    "Lali Espósito",         
    "Cecilia Roth",         
    "Daniel Funes de Rioja",         
    "Jeff Bezos",         
    "Héctor Olivares",         
    "Samar Badawi",         
    "Winston Churchill",         
    "Juan Grabois",         
    "Paula Oliveto",         
    "Francisco Gutiérrez",         
    "Matías Lammens",         
    "Sergio Palazzo",         
    "Ofelia Fernández",         
    "Hernán Lacunza",         
    "Lionel Messi",         
    "José Luis Espert",         
    "Guido Sandleris",         
    "Florencia Kirchner",         
    "Sasha Obama",         
    "Daniel Menéndez",         
    "Juan Carlos Alderete",         
    "Emilio Pérsico",         
    "Mariano Arcioni",         
    "Gisela Marziotta",         
    "Hugo Alconada Mon",         
    "Pablo Yapur",         
    "Maximiliano Ferraro",         
    "Gabriel Solano",         
    "Santiago Cafiero",         
    "Evo Morales"]

def findall(p, s):
    '''Yields all the positions of
    the pattern p in the string s.'''
    i = s.find(p)
    while i != -1:
        yield i
        i = s.find(p, i+1)

def find_entities(quote, text, entities=ENTITIES):
    sentence_position = text.find(quote)
    if sentence_position == -1:
        return

    splited = text.split(quote)
    entities_found = {}
    closest_distance = 100000000

    closest_entity = ""
    for entity in entities:
        for chunk in splited:
            for distance in findall(entity, chunk):
                print("Found entity at " + str(distance))
                entities_found[entity] = distance
                if distance > -1 and abs(distance-sentence_position) < closest_distance:
                    closest_distance = abs(distance-sentence_position)
                    closest_entity = entity
    
    print("QUOTE: " + quote + " | TEXT: " + text + "| CLOSEST ENTITY: " + closest_entity + " | DISTANCE: " + str(closest_distance))

my_text = [
    """La diputada  Elisa Carrió  estalló con la alianza Cambiemos con una serie de audios, al que llama que "son un asco". Contundentes definiciones contra sus socios, tras la derrota de Mario Negri en Córdoba. "Qué terrible es que en las derrotas se borren todos. Me dan asco", lanzó.  Tensión en Cambiemos por la caída del radical, quien quedó a 40 puntos del reelecto peronista Juan Schiaretti. LOS AUDIOS ESCANDALOSOS Para Lilita, hubo traición, abandono e indiferencia  para con el candidato radical al que ella apoyó públicamente y generó caos en su provincia. "¿Qué van a hacer si nos derrotan? ¿Se van a borrar? Yo no estoy para borrarme. Pero si esa es la política, sí estoy dispuesta a no estar", lanzó en una serie de escuchas que publicó hoy en sus redes sociales oficiales. Con tono durísimo, tiró Carrió: "Que el Gobierno nacional no se siente prescindente, porque los dirigentes de  Cambiemos  que pelean en las provincias también tienen que defender a un Gobierno que no puede obtener resultados económicos". Además, le pegó a un ministro de Mauricio Macri. "Cambiemos no acompañó a Cambiemos.  El ministro del Interior siempre hizo su sociedad con los gobernadores del PJ". Hablaba de Rogelio Frigerio . "La vida no es compartir el éxito y alejarse en la derrota. Me parece inhumano. Tenemos que reflexionar sobre cuánto le debemos a Mario Negri, cuánto tuvo que bancarse la indiferencia, la superficialidad, la falta de escucha. Falta de estrategia de Cambiemos nacional, que es una constante", cerró. """,
    """El  Sindicato de Empleados de Comercio  avanza en una negociación paritaria con las cámaras empresarias. Según pudo saber  El Destape , el objetivo es  conseguir un 30% de aumento  mediante una  recomposición salarial del 5% bimensual , pero aún el acuerdo no fue firmado y se resolverá en los próximos días. El acuerdo que se dividirá en segmentos de alrededor del 5% cada dos meses hasta abril de 2020 , según informó Clarín. Sin embargo, este medio pudo saber que la Federación Argentina de Empleados de Comercio y Servicios aún no confirmó si ese será el porcentaje a recomponer o si será mas y siguen las negociaciones. Además, la Confederación Argentina de la Mediana Empresa tampoco se pronunció al respecto y lo haría en los próximos días. De concretarse, la firma de la paritaria del sindicato que conduce  Armando Cavalieri  se convertiría en una referencia para el resto de las entidades de trabajadores, ya que posee gran peso en el mapa gremial debido al millón de afiliados que posee en el país. Desde el entorno de la CAME advirtieron que aun no fue homologado el acuerdo. Ante esto, la FAECYS señalaron que "va a ser así" y que "tecnicismos" son los que frenan la firma. """,
    """Diputados nacionales del FPV-PJ presentaron un proyecto para  impulsar el juicio político contra el ministro de Justicia y Derechos Humanos de la Nación, Germán Garavano,  por mal desempeño y eventuales delitos en el ejercicio de sus funciones. El pedido de juicio político está encabezado por los diputados  Rodolfo Tailhade, Agustín Rossi y Leopoldo Moreau  y se basa en “las presiones indebidas dirigidas a forzar la renuncia del  Dr. Carlos Rozanski  a su cargo de juez federal” y a “la negociación con el arrepentido  Leonardo Fariña  para garantizar el contenido de sus declaraciones en sede judicial” y direccionarlas en contra de la ex presidenta  Cristina Fernández de Kirchner. Tal como declaró Moreau esta mañana en Radio Cooperativa,  “quedó plasmado que (Garavano) ofrecía beneficios a delincuentes a cambio de que fraguaran declaraciones en expedientes contra Cristina Kirchner”.  El diputado explicó que hay "evidencias y grabaciones” que sitúan al funcionario en una reunión Fariña. Según fundamentaron los impulsores del proyecto, ésto comenzó el 29 de marzo de 2016 cuando Fariña recibió el primer mail indicándole qué debía declarar en sede judicial. En el orden cronológico, el próximo episodio ocurrió el 28 de abril, cuando el Consejo de la Magistratura votó la vuelta a comisión del expediente 54/13 contra Rozanski, por más que ya se hubiera vencido el plazo para tratarlo. LEER MÁS:  El audio de la extorsión de Garavano y Cabral a Rozanski “Por esto es que el 28 de junio, cuando se dio la  reunión entre Garavano, Fariña y (la abogada Giselle) Robles , el ministro les garantizó -entre otras cuestiones- que el Dr. Rozanski sería desplazado de su cargo”, afirmaron los diputados. Este hecho tuvo lugar el 20 de junio, un día después de que Rozanski se reuniera con Garavano y con el consejero de la Magistratura Luis María Cabral, quienes, como reveló El Destape, lo presionaron para renunciar. "Con la maniobra cerrada,  ni Fariña ni el Gobierno tendrían que volver a preocuparse por la intervención de un juez que no les servía  para la pata judicial de su aparato de persecución", argumentaron. Según la hipótesis de los legisladores del FPV-PJ, a través de su intervención personal Garavano logró dos cosas:  “Consiguió presionar a un juez federal para que presentara su renuncia  y así no interviniera en ninguna causa vinculada a un arrepentido en particular" por un lado y, por otro,  "que ese arrepentido siguiera declarando en otra causa judicial en la misma línea que lo venía haciendo , lo que implicaba seguir repitiendo lo que le llegaba en correos anónimos para así poder implicar a la ex presidenta Cristina Fernández de Kirchner”. """,
    """Se acercan las elecciones presidenciales y el primer debate tiene su fecha y lugar a realizarse y la decisión radicó que la sede será la Universidad Nacional del Litoral, en Santa Fe, el 13 de octubre.  Una semana después tendrá lugar en la Ciudad de Buenos Aires. El debate se hará después de las elecciones Primarias Abiertas Simultáneas y Obligatorias (PASO), con lo cual estarán los candidatos que hayan logrado atravesar esa instancia. El cierre de listas es el 22 de junio y las PASO se realizarán el 11 de agosto. Según confirmó el intendente de Santa Fe, José Corral, será en el Paraninfo, un espacio de la Universidad del Litoral, en la capital de Santa Fe. Es el mismo predio en donde se reunió la asamblea de constituyentes que modificaron la Constitución en 1994. En 2015 hubo un debate entre Macri y Scioli, pero esta será la primera vez que se realice a partir de la ley que establece la obligatoriedad de los debates presidenciales. Es la ley 27.337, sancionada en noviembre de 2016.                           """,
    """El Secretario General de gla Fraternidad, Alberto Fernández,  confirmó que los gremios de transporte  convocarán a un paro en la última semana de mayo o la primera de junio  y advirtió que el resto de  la  CGT  tiene voluntad de plegarse a la medida  en la reunión de Consejo Directivo que se realizará esta tarde: “De parte del transporte vamos a hacer un paro la última semana de mayo o la primera de junio", señaló. A la vez que confirmó que  “hay voluntad” en el resto de los dirigentes de la cúpula porque “las condiciones para un paro están a la orden del día”. En diálogo con el programa  “Navarro 2019”  por  el Destape Radio ,  el gremialista dio detalles de la reunión de ayer  entre la CGT y el FMI y advirtió que “el FMI nos dijo que la inflación va a bajar en el segundo semestre"  y que “el FMI nos dijo que van a ayudar a este gobierno o el que venga". Además, aclaró: “En el FMI nos dijeron que ya le dieron al gobierno 90% del préstamo, quedan apenas 5.000 M de USD para el 2020, cuando vamos a tener que empezar a pagarlo”. Por otra parte y en torno al panorama político, Fernández afirmó: “"Estamos más cerca de Lavagna. Creemos que él va a ser el candidato del peronismo", indicó que “nos llevamos mal con Cristina, nos cobraba impuesto a las ganancias" y advirtió que “si Cristina se baja, podemos unirnos todos”. """,
    """El abogado  Miguel Ángel Pierri confesó que el portero  Jorge Mangeri  mató a Ángeles Rawson. Fue el abogado defensor del encargado del edificio  condenado a reclusión perpetua . Mientras lo era, concedió una entrevista a la TV en 2013 donde su hijo lo expuso a Pierri. Ahora lo reconoció el propio Pierri. Fue durante la obra de teatro que encabezan los periodistas  Mauro Szeta y Paulo Kablan . Allí entrevistan a personajes de la Justicia y policiales. Ayer estuvo Pierri y contó finalmente que Mangeri fue quien  mató a la adolescente Ángeles Rawson el 10 de junio de 2013, en el barrio porteño de Palermo. En octubre en 2013, se puso en aprietos a Pierri en una entrevista que brindó en un canal de cable e incluso su hijo lo obligó a aclarar la particular situación difundida en vivo. El curioso episodio ocurrió en los estudios del Canal Metro, en el programa Contámelo todo, que conduce Leo Rosenwasser, el ex humorista de Video Match ya fallecido, Pierri hablaba sobre el caso Angeles. Pero  "Juancito", su hijo, que casualmente estuvo a su lado durante toda la entrevista, lo expuso. Rosenwasser preguntó sobre la inocencia de Mangeri. “Mangeri es un señor inocente que está pasando el peor momento de su vida”, respondía el letrado cuando imprevistamente fue interrumpido por su hijo:  “Pero boludo, (Mangeri) mató a Angeles...” (sic), dijo el nene de 7 años. Pierri lo calló.  """,
    """El rapero  Wos  conmovió a todo el público en los Premios Gardel 2019, con su sentido freesyle en el homenaje a Mercedes Sosa. Este año, el Gardel de Oro fue otrogado a la cantante de rock Marilina Bertoldi, quien es la segunda mujer en ganarlo en la historia, antecedida por la eterna cantante de folklore. Antes de presentar el galardón, se realizó un homenaje a Mercedes Sosa, con la participación de Teresa Parodi, Victor Heredia, Luciana Jury y el rapero Wos, que hizo una emocionante improvisación en el acto. EL FREESTYLE COMPLETO Si hay razones pa vivir, entonces que sea una ésta Buscando en el arte respuesta para esa existencia que tanto nos cuesta Traje versos de la calle y este brebaje de apuestas ¿Quién dijo que todo está perdido? A los pibes nos sobra la fuerza A las pibas le sobra la fuerza, aunque todo este jodido A los pibes nos sobra la fuerza, para ganar el partido No digas que todo está perdido, todavía nos sobra la fuerza para ganar el partido Sueno campeón por rapear, vengo a ocupar un lugar, vengo a bailar, a vacilar A defender la memoria de esa que hace tiempo nos quieren robar Los dinosaurios que siempre la ponen oscura con su mano dura De esos que te prometen un cambio y en cambio están matando a la cultura El tiempo puede pasar, su voz sigue siempre presente, en la gente que quiere en verdad la unión de todo un continente el tiempo puede pasar pero su voz sigue siempre igual Documento inalterable de nuestra identidad """,
    """El analista Jorge Asís protagonizó un delirante momento durante el cierre de una entrevista, en la que le dejó un duro mensaje a uno abogado del Gobierno. Tras participar de una charla mano a mano con  José del Río , el ex panelista de Animales Sueltos notó que participaría el abogado  Alejandro Fargosi  e hizo un comentario mientras se retiraba. "A ustedes les digo que está ya aquí el señor de la justicia, vamos a hablar con Fargosi" , dijo el conductor, a lo que Asís contestó:  "Bueno, me voy entonces".                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   """,
    """El juez  Alejo Ramos Padilla  procesó el pasado miércoles al fiscal  Juan Ignacio Bidone  por integrar una asociación ilícita del falso abogado  Marcelo Sebastián D’Alessio . Se trata del segundo procesamiento en contra de quien fuera el fiscal de la causa conocida como el Triple Crimen de General Rodríguez. El procesamiento es sin prisión preventiva, como así también se confirmó el embargo "sobre los bienes del antes nombrado hasta cubrir la suma de  diez millones de pesos ". "Se ha corroborado prima facie que, en connivencia con otros imputados – Marcelo D´Alessio y Rolando Barreiro -, el Fiscal de Mercedes llevó adelante actividades de investigación e inteligencia criminal en perjuicio de numerosos ciudadanos/objetivos de la organización investigada", argumenta el fallo. Es el segundo procesamiento que sufre Bidone tras la resolución de hace algunos días del juez Luis Rodríguez en la causa en la causa que investiga una supuesta extorsión por parte del ya detenido D'Alessio al empresario aduanero Gabriel Traficante. Este es el segundo procesamiento contra el fiscal del Triple Crimen, luego del que dictara el juez federal de Comodoro Py, Luis Rodríguez, acusado de " infringir temor suficiente sobre Gabriel Traficante" para pedirle un pago ilegal de 90.000 dólares a cambio de influir para beneficiarlo en una causa judicial , la de la llamada "mafia de los contenedores". """,
    """El sindicalista  Hugo Moyano  le respondió a un cronista de  Todo Noticias quien objetó la visita de la senadora de Unidad Ciudadana  Cristina Kirchner  a la sede del  Partido Justicialista.  "Antes Cristina decía que el PJ era un sello de goma. ¿Qué pasó entre una cosa y la otra?", chicaneó el cronista de TN. "Los peronistas somos así: a veces decimos una cosa, otra veces decimos otra. Lo importante es que cuando los pueblos, los laburantes y los humildes nos necesitan  estamos todos juntos" , la respondió Moyano. La ex presidenta participó de la cumbre del  Partido Justicialista  celebrado en la calle  Matheu , donde se hablo de la necesidad de ganar las próximas elecciones presidenciales y el descalabro económico que dejará el gobierno de  Mauricio Macri.                                                                                                                                                                                                                                                                 """,
    """Cristina Kirchner recibió un emotivo video  sobre su libro "Sinceramente" y eligió compartirlo en sus canales oficiales. Está realizado por la Asociación Mutual Homero Manzi, donde chicos y adultos leen fragmentos del boom editorial del momento: el libro de la senadora. El video se lo mandó el periodista Fernando Borroni a  Carlos Zannini , ex funcionario de su gobierno. Y el "Chino" se lo envió ayer a la ex mandataria. Cristina decidió hacerlo público. Y emocionada, comentó en sus redes: "A ellos y a ellas, muchas gracias… de corazón".                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   """,
    """El ex gobernador de Entre Ríos,  Sergio Urribarri relató detalles de la reunión del PJ el martes 14 de mayo: “Cristina desarrolló y explicó los escenarios posibles, hizo un repaso de las consecuencias de las políticas del Gobierno de Macri,  se puso a disposición de un gran frente”. En diálogo con el programa  “Habrá consecuencia”  de  El Destape Radio , Urribarri relató que  "Cristina definió que esta sí va a ser una pesada herencia”  y que le encantaría que la ex presienta se postulara. “Pero hay que tener paciencia, esperar su decisión”, aclaró. Sobre la ampliación del frente de unidad, el entrerriano afirmó que “no está para nada cerrada la posibilidad de que  Sergio Massa  integre este espacio. Él no ha sido muy claro en lo que quiere hacer, pero muchos vemos que su lugar está acá”. “Algunos de los que estaban ayer se habían distanciado. Pero lo importante es ver qué pone cada uno para que Macri se vaya el 10 de diciembre”, agregó. Asimismo, Urribarri adelantó que “es importante una foto con más Gobernadores. La de ayer era con la Comisión de Acción Política con Cristina y estaban todos. Lo que viene es otra convocatoria con otros Gobernadores”. En ese sentido, Urribarri, afirmó que vio la foto de Frigerio y Pichetto: “ Tenían cara de tristeza.  Como si estuvieran viendo un partido de fútbol y su equipo perdiera 4 a 0”. """,
    """El analista político  Jorge "El Turco" Asis  cuestionó la vinculación entre el kirchnerismo y la  Venezuela  de  Nicolás Maduro,  al considerar que fueron procesos políticos diferentes que sólo compartieron un tiempo de gestión. "Macri se quedó sin rumbo económico y está sostenido por un  Donald Trump  que tiene muy mala información. El gran problema de Estados Unidos es que tienen malas interpretaciones de informaciones inexactas:  creen que el kirchnerismo tiene algo que ver con el bolivarismo ", afirmó. El conductor de  La Nación +  preguntó si no había entonces vinculación entre  Nicolás Maduro y el kirchnerismo : "Por su puesto que coincidieron en un tiempo histórico: se comieron el cuento de la revolución imaginaria del kirchnerismo y en realidad lo único que falta es que vayan a buscar a Santa Cruz armas de destrucción masiva". Asís  explicó que el kirchnerismo pagó todas las deudas que tenía la Argentina: "fue un pagador serial, pagó todo lo que tenía que pagar. Pagó incluso más de lo que debía pagar". El analista político afirmó que  el macrismo tomó más de 120.000 millones de dólares de deuda externa . "Dónde están los transatlánticos, los portaviones, qué se modernizó. Fueron 120.000 millones de bicicleta financiera", sostuvo. """,
    """Como todos los días, el conductor del segmento la primera mañana  Sergio Lapegüe  se juntó con  Adrián Ventura  para analizar los temas más importantes para  Todo Noticias  sobre la jornada anterior y decidieron omitir un tema sumamente importante para atacar a  Cristina Kirchner . El columnista había iniciado su análisis afirmando que el martes había sido “un día a la medida de Cristina”,  ya que por la tarde se dio la viral foto del PJ unido con  ella como su figura en el centro de la escena  y por la decisión de la Corte de pedir el expediente de la causa por la obra pública, lo que retrasaría su juicio oral. Sin embargo, esa noticia no estaba en la rutina de Ventura y en su lugar figuraba la inflación de abril sería del 4%:  “El tema que falta, la Corte, lo único que faltaba… ah no, bueno. Lo agregamos ”, aseguró y comenzó a hablar al respecto.  En Paralelo, la cámara hizo zoom para que el título de los aumentos quedara tapado. “Bueno, después vamos a hablar de esto, pero esta era la inflación cuatro puntos”, le recordó Lapegüe. """,
    """Como adelantó el periodista  Horacio Verbitsky  en  El Destape Radio  hace casi dos semanas, cuatro de los cinco jueces que integran la  Corte Suprema de Justicia  firmaron una resolución que retrasará el inicio del juicio a   Cristina Kirchner  por irregularidades en la  obra pública. "Es posible que este año que es electoral  no haya juicio oral contra Cristina Kirchner.  La Corte Suprema de Justicia está tratando ese tema. Se insinúa esa tendencia de postergar los debates orales", sostuvo Verbitsky en el programa  Habrá Consecuencias  en  El Destape Radio  el 3 de mayo. Tal como lo anticipó el periodista, con excepción de  Carlos Rosenkrantz , los jueces  Ricardo Lorenzetti ,  Horacio Rosatti ,  Juan Carlos Maqueda  y  Elena Highton  tomaron nota de los reclamos de la senadora y solicitaron, con carácter de urgente, el cuerpo principal de la causa "Vialidad" al Tribunal Oral Federal 2 para su análisis, atendiendo a una serie de reclamos procesales de la ex presidenta y otros imputados. "Había una idea en Cambiemos que mostrar a la ex presidenta en el banquillo de acusados hacía que pierda totalmete atractivo electoral y favorecía la reeleeción de Macri.  Hoy está claro que entre más le tiran, más la fortalecen ", sostuvo el periodista hace casi dos semanas. Una vez que la Corte tenga el material solicitado,  el máximo tribunal lo analizará "lo más rápido posible" la causa para que la demora del juicio sea breve.  Según una nota del diario Clarín, el objetivo de la Corte es "evitar futuros pedidos de nulidad de las actuaciones" y la dilación del enjuiciamiento se podría deber a que las audiencias difícilmente puedan comenzar antes de las elecciones primarias de agosto, plazo que podría extenderse hasta fin de año. LEER MÁS:  Elecciones: CFK se puso a disposición de armar una "coalición grande" """,
    """Después de que  Elisa Carrió acusara a los dirigentes PRO de haberle soltado la mano a Mario Negri  tras la aplastante derrota de las elecciones en Córdoba, el ministro del Interior,   Rogelio Frigerio , y el jefe de Gabinete  Marcos Peña le respondieron  y buscaron bajarle el tono al duro enfrentamiento. La líder de la Coalición Cívica publicó una serie de audios en redes sociales en el que aseguró que su partido estuvo "el día de la derrota en Córdoba" porque "la vida es lucha y adversidad, no es compartir el éxito y alejarse en la derrota" y aseguró que es "inhumano" y "servil" hacer ésto último. Lilita resaltó que  ella apoyó al candidato que supo apoyar al Gobierno de Cambiemos "y al que muchos abandonaron" tras la derrota  y pidió "reflexionar" sobre cuánto se le debe a Mario Negri en el interbloque oficialista de Diputados. "Ella plantea que los Ministros o el Poder Ejecutivio tendrían que haber ido más a la provincia (de Córdoba)", respondió Frigerio.  El Ministro aseguró que ellos tomaron "la decisión de no participar en la campaña porque Cambiemos fue dividido  y no correspondía". Carrió había asegurado que Cambiemos no apoyó a Cambiemos en ese distrito y que "Frigerio siempre hizo su sociedad con gobernadores del PJ". Peña, en tanto, usó la red social Twitter para responderle a la diputada cofundadora de Cambiemos:  "Creemos en una política humanista, transformadora de la realidad, transparente y al servicio de los ciudadanos.  Ese fue siempre el mandato y el espíritu de Cambiemos. Seguiremos trabajando para lograrlo en cada lugar del país". LEER MÁS:  Elecciones 2019: Cambiemos aceptó la dura derrota de Negri y Mestre """,
    """Los buenos resultados de las elecciones a gobernador en Córdoba pintaron una sonrisa en el rostro de  Omar Perotti . Salvando las distancias en las configuraciones e historia del PJ de ambas provincias, no hay dudas de que el octavo golpe consecutivo para Cambiemos y el hecho de que el peronista  Juan Schiaretti  haya sacada una victoria abultada le da a la fuerza política una sensación de racha que, de repetirse en  Santa Fe , podría asestar una estocada mortal al sueño releeccionario de  Mauricio Macri . Para seguir de racha, encima sumó la foto de unidad que tanto buscaba con  María Eugenia Bielsa , justo el día en que  Cristina Kirchner  se sacó la foto de unidad en el Consejo Nacional del PJ. Si bien es un error nacionalizar los resultados provinciales, no es menos verdad que la situación del país se inmiscuye en las elecciones de los distritos. Esto es lo que le pasó a Cambiemos, que perdió 200 mil votos en Santa Fe entre las PASO 2015 y las del último 28 de abril. Desde que es gestión en Nación, el PRO pasó en la provincia de cosechar 536 mil votos a 322 mil, 214 mil menos. La marca Cambiemos que le dio tantos éxitos hace dos años en las legislativas de medio término es hoy un lastre. Al mismo tiempo, el resultado positivo de la PASO en Santa Fe más lo sucedido en la provincia mediterránea lo posiciona mejor al rafaelino de cara al 16 de junio. La recuperación del socialismo (Antonio Bonfatti obtuvo el primer lugar como candidato) se dio a partir de la debacle económica del macrismo. Pero el PJ también se revitalizó enormemente bajo el mismo proceso desde la última elección Ejecutiva: saltó de 365 mil a 704 mil sufragios desde las primarias de hace 4 años. La estrategia de Cristina de bajar sus propios candidatos y trazar una alianza con Perotti demostró ser exitosa: el rafaelino es un candidato robusto que imantó votos de distintos sectores, incluso de los productivos del agro del interior de la provincia que se habían divorciado del kirchnerismo. Bielsa, que perdió la interna justicialista pero se mantiene activa, sorprendió con marcados gestos públicos de apoyo a Perotti, a quien había castigado un poco durante la campaña. Primero vino un comunicado, y luego con la presencia de su principal candidata a diputada, Silvina Frana, y el candidato a senador por Rosario Marcelo Lewandosky (ganó la interna a la representante de Perotti) en diversas actividades de campaña junto al contador. Pero los rumores de distanciamiento de la exvicegobernadora de su rival en las PASO terminaron de sepultarse este martes, cuando se retrataron juntos compartiendo un café en un bar de Rosario ubicado en el barrio de la arquitecta. Quienes rodean al senador confían en que estos mensajes engorden la cantidad de votantes que eligieron a Bielsa en las primarias y elijan permanecer dentro del caudal del Frente Juntos, lo que estiman arriba del 70 u 80%. “La comunicación entre los equipos es constante. Ellos hablan y se reúnen”, afirma un asesor. Entre bambalinas se comenta que Bielsa ya pidió para su sector un ministerio (sería Desarrollo Social) y la creación de una suerte de Oficina Anticorrupción provincial. Pero además de los que apoyaron a la rosarina, tiene que ir por los que no votaron en las primarias y los que lo han hecho por otras opciones. “Hay que ir a hablarle a todos los que en otra oportunidad votaron otras fuerzas políticas y están desencantados”, sostiene un asesor, que además admite que “Omar” seguirá con el mismo discurso moderado, sin estridencias, que practicó durante la campaña antes de abril, con especial hincapié en el tema de la inseguridad y la producción. “¿Vos alguna vez lo escuchaste hablar distinto?”, pregunta de forma socarrona ante la consulta de este medio. Pero tiene razón: Perotti siempre fue un equilibrista y hay tantas probabilidades de que kirchnerice su discurso como de que el cielo deje de ser celeste. La búsqueda será sobre los 5 a 8 puntos que se estima se incorporarán con la gente que vota en esta elección y no concurrió en la anterior. Bajo este panorama, para colmo Lifschitz y Bonfatti renovaron sus disputas internas: el presidente de la Cámara de Diputados le recriminó al gobernador que su aventura por la reforma constitucional le estaba sacando energía a la campaña, al igual que pasó en las internas de Rosario donde el socialismo perdió con el radicalismo progresista, que se llevó gran parte de los esfuerzos del partido en las PASO. Esa fue la verdadera razón detrás de la decisión de bajar la consulta, que el peronismo –acusado de culpable del fracaso por Lifschitz- propuso establecer por ley y el gobernador intentaba por decreto. De hecho, en la Legislatura hay cinco proyectos presentados, 3 de los cuales son del justicialismo. La puesta en escena, más que esconderla, hizo más visible la tensión: el exintendente rosarino apareció en la conferencia de prensa con toda la dirigencia atrás para que no parezca una claudicación personal hacia la otra rama del partido y la oposición, sino una cuestión de republicanismo. Pero la intención ya se sabía casi muerta de antemano. Especialistas habían advertido que la consulta enturbiaba el proceso eleccionario y que esa potestad corresponde a la Legislatura. La oposición había salido a decir que impugnaría el proceso ante el Tribunal Electoral. De hecho, el diputado del PJ Leandro Busatto lo calificó en contacto con El Destape como “un papelón jurídico e institucional”. “Siempre que el socialismo fracasa en algo culpa a otro partido, esta vez nos tocó a nosotros”, dijo quien encabeza la lista de legisladores del frente Juntos. Este movimiento errático también denotó cierto nerviosismo dentro de una fuerza que gobierna hace 12 años y estuvo a dos mil votos de perder la última elección. Hoy, todos los operadores intentan buscar una manera de captar votos por derecha (Corral) e izquierda (Bielsa). Pero la postura pública de Bielsa en apoyo a su contrincante de interna achicó los márgenes de votos que no pasarían de uno a otro y se irían a otra fuerza. Apenas después de las PASO, en el Frente Progresista especulaban que se quedarían con la mitad de los votos de la arquitecta en la general. Hoy, luego de los gestos amistosos de ambos dirigentes peronistas, creen que serán uno de cada tres. “La izquierda no vota ni a palos a Perotti ni a Corral, hay que ver si robás algo de ahí. Y me imagino a Corral desinflándose porque quedó lejos y hay un gorilismo que jugará para nosotros. Son 20 puntos, si le robamos 2 ya está. El que votó Macri no vota Cristina”, dice un asesor del socialismo, donde creen sin embargo que la disputa será “difícil” y palo a palo con el PJ. A su vez, Lifschitz intenta buscar una salida a nivel nacional por tercera vía con Lavagna, Schiaretti (encumbrado por su abultado triunfo) y el peronismo alternativo para proyectarse a si mismo fuera de la provincia y para que la identidad del socialismo no quede oprimida entre los polos K y M. Ya sin la ciudad de Rosario, donde formará parte del gobierno en segundo plano, con posibilidad de perder la provincia y sin referencias nacionales fuertes tras el ocaso de Hermes Binner, esa identidad corre riesgo de desaparecer. Por eso estos meses serán fundamentales para el partido de la rosa. Ya veremos. *Nicolás Maggi es corresponsal de El Destape en Santa Fe. """,
    """El ex jefe de Gabinete  Alberto Fernández  cruzó a la titular de la  Oficina Anticorrupción (OA)   Laura Alonso,  luego de que la Corte Suprema frenara el inicio del juicio contra la senadora de Unidad Ciudadana,   Cristina Kirchner ,  por falta de revisión de los expedientes y las pruebas. El ex funcionario le recordó a Alonso que ocupa la OA sin ser abogada. "En una escandalosa resolución con olor a Alberto Fernández en busca de impunidad para la ex Presidenta, la Corte Suprema toma una inédita medida. Esperamos que el Tribunal Oral INICIE el juicio la semana próxima porque NO hay fundamento para que no lo haga  # ObraPública ", escribió la imputada  Laura Alonso.  "Para  @ lauritalonso  es “escandaloso” que la Corte pida un expediente por un recurso de queja.Habla así porque no es abogada y desconoce el derecho. Ignorancia pura. Ahora, si puedo unir a casi toda la Corte detrás de una decisión, unir a la oposición va a resultar una pavada", le respondió Alberto Fernández.  Con excepción de  Carlos Rosenkrantz , los jueces  Ricardo Lorenzetti ,  Horacio Rosatti ,  Juan Carlos Maqueda  y  Elena Highton  tomaron nota de los reclamos de Cristina Kirchner y solicitaron el martes el cuerpo principal de la causa "Vialidad" al Tribunal Oral Federal 2 para su análisis, atendiendo a una serie de reclamos procesales de Cristina Kirchner y otros imputados """,
    """El gobernador de  Salta ,  Juan Manuel Urtubey , participó junto al presidente del Consejo Económico y Social de la Ciudad Autónoma de Buenos Aires,  Matías Tombolini , de una reunión del organismo salteño y calificaron como “muy valioso” el intercambio de experiencias en base a una agenda común de temas. “Hoy se habla de consenso, diálogo o el hashtag que mejor le convenga al gobierno nacional para tratar de impulsar una agenda en la que no cree”, afirmó Tombolini y enfatizó: “Nosotros sí creemos en eso”. Luego compartió su experiencia en el Consejo Económico y Social de CABA “que tiene una larga tradición en el diálogo” y manifestó que tiene mayor valor “cuando se practica con quien piensa distinto, no con quien piensa del mismo modo”. En esa línea, Tombolini sumó: “En la idea de impulsar esta agenda común, me invitó Juan Manuel a compartir una reunión del Consejo de Salta, que es uno de los más importantes de la Argentina”. Urtubey destacó la presencia de Tombolini en Salta para compartir su experiencia en el Consejo Económico y Social de CABA remarcando la coincidencia de impulsar la institucionalización de este órgano consultivo a nivel país. “Creemos que, juntos, con la Ciudad de Buenos Aires como la principal caja de resonancia de la Argentina, podemos dar un paso importantísimo para que, en no mucho tiempo más, estemos asistiendo con gran satisfacción a la constitución de un Consejo Económico y Social para toda la Argentina”, aseguró el mandatario. El precandidato a presidente por Alternativa Federal pone este objetivo en la cabeza de sus propuestas desde que dio a conocer sus intenciones de participar en las próximas elecciones para ocupar el sillón de Rivadavia. “Es necesario canalizar la vocación de participación ciudadana, que en nuestra democracia es cada vez mayor, y el mecanismo para hacerlo es sin dudas el Consejo Económico y Social”, afirmó Urtubey. """,
    """Cuatro de los cinco jueces que integran la Cortge Suprema de Justicia firmaron una resolución que le pone puntos suspensivos al primer juicio que debía enfrentar la expresidenta  Cristina Kirchner  antes de las elecciones por presuntas irregularidades en la obra pública vial de Santa Cruz. El juicio debía comenzar el 21 de mayo, pero el Tribunal Superior solicitó el expediente para revisarlo. Semanas atrás, el periodista  Horacio Verbitsky   lo había adelantado en  El Destape . Con excepción de  Carlos Rosenkrantz , los jueces  Ricardo Lorenzetti ,  Horacio Rosatti ,  Juan Carlos Maqueda  y  Elena Highton  tomaron nota de los reclamos de Cristina Kirchner y solicitaron, con carácter de urgente, el cuerpo principal de la causa "Vialidad" al Tribunal Oral Federal 2 para su análisis, atendiendo a una serie de reclamos procesales de Cristina Kirchner y otros imputados. Una nota de Clarín advierte que en la Corte buscan "evitar futuros pedidos de nulidad de las actuaciones". “Por disposición del Triunal, solicítense los autos principales con carácter de urgente”, reza la resolución 5048//2016 que se rubricó tras la reunión de acuerdo de ministros que se realizó este martes. Con esas pocas palabras,  el Tribunal Superior provocó un sismo político al interrumpir el proceso que debía iniciarse el 21 de mayo  e iba a tener a la senadora por Unidad Ciudadana sentada en el banquillo de los acusados. En los pasillos del cuarto piso del Palacio de Talcahuano aseguran que difícilmente se retome antes de los comicios. Entre los recursos y apelaciones solicitados por la ex Presidenta y otros imputados se advierte que no le hicieron lugar a varias de las medidas de prueba que pidió, como la recordada pericia sobre toda la obra pública licitada en los tres gobiernos K, aunque no pesen denuncias ni investigaciones sobre esos contratos. Una vez que tenga el material solicitado, el máximo tribunal lo analizará "lo más rápido posible", para que la segura demora del juicio sea lo más breve que se pueda. En la misma nota se señala que la demora del juicio se debería a que las audiencias difícilmente puedan comenzar antes de las elecciones primarias de agosto, plazo que podría extenderse hasta fin de año. """,
    """Sentado en el 54% de los votos que le permitieron, además de su reelección, conseguir el 75% de la Legislatura –tendrá mayoría agravada- y gobernar la ciudad de Córdoba, el gobernador  Juan Schiaretti  dijo hoy que se reunirá con el presidente   Mauricio Macri  para dialogar sobre los 10 puntos de consenso que impulsa, con desespero, la Casa Rosada : “Si me llama, por supuesto que me voy a reunir”,  aseguró y hasta se dio el lujo de bromear sobre sus compañeros de Alternativa Federal : “Yo pertenezco a un espacio que decidirá el momento, soy simplemente el gobernador de Córdoba que ha sido elegido por los cordobeses, pero no soy el dueño ni el macho alfa de Alternativa Federal”. El gobernador también negó que su aplastante victoria –le sacó 36% de diferencia a Mario Negri- sea un trampolín para lanzarse a la Casa Rosada:  “Cómo voy a hacer esas especulaciones. Estoy acá en Córdoba trabajando. Muchos me dicen 'es el único gobernador que venció por tanto margen y no está instalado en Buenos Aires haciendo prensa'. Yo me debo al pueblo cordobés y por lo tanto sigo trabajando acá para Córdoba.  Ya llegará el momento de hablar de las elecciones nacionales y allí obviamente daremos nuestra opinión”. Sobre el futuro del peronismo,  Schiaretti sostuvo que promoverá ir a las PASO de agosto con el ex ministro Roberto Lavagna, Sergio Massa y su par salteño Juan Manuel Urtubey  y que todos lleven listas comunes a legisladores nacionales. Cuando le preguntaron por la confluencia de Alternativa Federal con la ex presidenta  Cristina Fernández de Kirchner , respondió que “hay otros espacios políticos que se pueden reunir pero eso se verá en el momento oportuno". Al respecto, señaló: "Yo dialogo con todo el mundo, pero  el kirchnerismo es otro espacio político.  Jamás voy a negar el diálogo a ningún espacio politico diferente al nuestro”. El presidente del PJ Nacional,  José Luis Gioja,  había propuesto una PASO de todo el peronismo, pero Schiaretti lo relativizó: “Pertenezco a un espacio que decidirá en el momento en que lo considere adecuado. Soy simplemente gobernador de Córdoba, que ha sido elegido por los cordobeses,  no soy el dueño de Alternativa Federal” . Agregó que tampoco habló con sus compañeros nacionales del futuro del peronismo no kirchnerista: “Ya habrá tiempo, hasta ahora no hemos hablado con ninguno. Falta bastante para que haya que presentar las listas de los que compiten a presidente”. El día antes del cierre de listas en Córdoba,  Máximo Kirchner  llamó a su compañero de bancada en Diputados, el cordobés Pablo Carro y le ordenó  que Unidad Ciudadana baje sus listas  en la provincia mediterránea. Incluso la diputada nacional y líder de La Cámpora Córdoba,  Gabriela Estévez llamó a votar al PJ:  “Es difícil para mí plantear votar a (Juan) Schiaretti y a (Manuel) Calvo, yo lo que digo es que  entiendo que hay que votar al peronismo, que hay que votar a la fuerza opositora que más votos nuclea y que puede representar para el gobierno nacional una pérdida muy importante , un fracaso muy importante en una provincia que lo apoyó a Macri mayoritariamente". En ese contexto, manifestó: "La opción a votar es el peronismo, yo no estoy llamando a los electores a votar por un candidato, pero es el análisis que yo hago y no es solamente el mío sino que va en una línea”. LEER MÁS:  Córdoba: Schiaretti logró una fuerte victoria y se alejó de la grieta Martín Fresneda , legislador K y ex secretario de DDHH de la Nación durante el gobierno de Cristina Fernández,  también llamó a votar por Schiaretti:  “Voy a votar al peronismo. He pensado mucho después que no constituimos una opción por una definición estratégica de la conducción nacional. Sin duda,  los que somos peronistas para mí tenemos que acompañar al peronismo”. En su primer encuentro con los periodistas después del triunfo del domingo, Schiaretti volvió a tenderle una mano a su socio estratégico, el presidente Mauricio Macri y no nacionalizó los resultados:  “Los cordobeses distinguimos a la hora de votar.  Elegimos quien puede ser mejor intendente cuando votamos a un intendente; quien mejor puede ser la persona que lleve la gobernación cuando votamos a gobernador y también a la mejor persona que creemos que puede ser presidente”. También colectivizó la victoria: “Estoy agradecido con el trabajo que vienen haciendo todos los miembros del gobierno (de la provincia).  Creo en la construcción colectiva.   Este no es el triunfo de Schiaretti porque sea gran cosa. Soy cordobés hasta el caracú y en el fondo siempre voy a ser un muchacho de barrio.  Este es un triunfo de un equipo y del pueblo de Córdoba”.  LEER MÁS:  Elecciones: CFK se puso a disposición de una "coalición grande" *Gustavo Molina es corresponsal de El Destape en Córdoba. """,
    """El secretario General de  SMATA ,  Ricardo Pignanelli,  anticipó que luego del anuncio de la CGT del paro del 29 de mayo, se juntará con el Frente Gremial a tomar una decisión frente a esa protesta. En diálogo con el programa  “Habrá consecuencias”  de   El Destape Radio , Pignanelli relató que “la reunión en el PJ fue muy buena. La compañera Cristina presentó su punto de vista de lo que va a tener que afrontar cualquier Gobierno que venga”. En ese sentido, afirmó que “faltan un par de pasos más para la unidad. Ojalá estuvieran todas las caras” y que “Sergio Massa tendrá que tomar una decisión. Hay varios que tienen que pensar si quieren ser parte de todo o todo de nada”. “Quiero una fuerza opositora donde estuvieran  Cristina, Massa, Duhalde, Lavagna” , sentenció.                                                                                                                                                                                                                                                          """,
    """El Servicio Nacional de Sanidad y Calidad Agroalimentaria (SENASA) comunicó la decisión de  aceptar la desvinculación de Giselle de los Ángeles Tasin Pavan,  la jefa de Recursos Humanos que se filmó practicando para despedir empleados e incluso acusarlos. "Acéptese la renuncia presentada por la Técnica Universitaria en Gestión de Recursos Humanos Da Giselle de los Ángeles TASIN PAVAN, al cargo de Directora de Recursos Humanos", expresó la resolución 521/2019, en el Boletín Oficial. Según la publicación, fue la misma funcionaria quien presentó la renuncia  por "razones particulares ", y no se deja asentado un mal desempeño luego del polémico video y los múltiples  despidos  mientras ocupó el cargo. En enero de 2018, se difundió un video en donde Giselle de los Ángeles Tasin Pavan se encontraba memorizando un discurso para poder despedir con facilidad a empleados. Unos días después despidió a 130 trabajadores.                                                                                                        """,
    """El dirigente peronista  Julio Bárbaro  reconoció que si en las próximas elecciones debiera elegir entre  Mauricio Macri  y  Cristina Kirchner optaría por la senadora de Unidad Ciudadana.  "Entre Cristina Kirchner y Macri , hoy votaría por Cristina . Aunque trataría de no votar, tengo 77 años y puedo no votar", afirmó Bárbaro. La frase resuena en el mundillo político debido a que Bárbaro fue uno de los pocos dirigentes peronistas que  reconoció haber votado a Mauricio Macri en el balotaje  ante Daniel Scioli en el 2015. "No hay ninguna posibilidad de que gane las elecciones, es un pobre tipo que vive el día a día, y el único gesto de grandeza de Mauricio sería correrse y dejarle lugar a  María Eugenia Vidal,  y echar a Marcos Peña para empezar a hablar", afirmó en una entrevista con Luis Novaresio en A24.                                                                                                                                                                                                                  """,
    """La Justicia de  Corrientes ordenó al intendente del departamento de Mburucuyá,  Pablo Guastavino , que informe las razones por las que  mantiene precarizados a los cuatro concejales opositores  desde hace 2 y 4 años en un escándalo por irregularidades que desató una investigación judicial. Los cuatro concejales opositores de la ciudad correntina de Mburucuyá, tres justicialistas y uno del partido Renovador,  están "en negro", sin obra social ni aportes jubilatorios , desde que asumieron en 2015 y 2017, sin lograr que el Ejecutivo local, en manos de  ECO- Cambiemos , escuche sus reclamo de "blanqueo". Bajo apercibimiento, la jueza en lo Contencioso Administrativo,  María Gabriela Romero Feris,  le dio al jefe comunal un plazo de ocho días para que informe las razones por las que se niega a registrar a los opositores con los aportes a la obra social Ioscor y la caja de jubilaciones IPS. Se trataría de  una "discriminación política"  que desencadena una investigación judicial por las irregularidades de funcionario público que ello implica, consideró la magistrada en la intimación enviada al municipio correntino. "La Justicia comenzó a investigar al intendente Guastavino, que es parte de un clan familiar que persigue a opositores, ya que se niega a regularizarnos cometiendo una grave irregularidad de funcionario público", explicó el concejal peronista  Gustavo Aromí  en declaraciones a la prensa. Según afirmó el dirigente del PJ, "la Municipalidad tiene la obligación de declarar ante la  AFIP  el alta de todo su personal, pero el intendente no lo hace porque se maneja con impunidad como parte de su clan familiar que no tiene ninguna cuenta en orden en Mburucuyá". Y agregó: "El clan Guastavino ya tuvo otros problemas con la Justicia porque en 2018 la Cámara en lo Contencioso y Administrativo de Corrientes condenó al intendente a presentar balances de cuentas de años anteriores y la planilla de trabajadores de la Comuna". Ahora, la Justicia vuelve a poner la lupa sobre la gestión municipal por una medida cautelar iniciada por los concejales Aromí, Marcelo Romero, Mario Soto y Franco Cáceres. "Esta vez, Guastavino suma otro hecho vergonzoso porque su gestión hace que el Municipio de Mburucuyá ni siquiera regularice los aportes de los concejales, además de otras deudas y cuentas negras que se investigan", expresó Aromí. """,
    """Francisco Muñiz , detenido hoy por intentar entrar a  Casa Rosada  con un arma,  le regaló una cuchilla grande a  Mauricio Macri  el año pasado y tres cuadros  para destinar al entonces Ministerio de Desarrollo Social. Según consta en el registro de  "Obsequios y viajes"  de la Oficina Anticorrupción, el supuesto atacante ya le había dado regalos al Gobierno para el cual milita: el 16 de abril de 2018 le entregó  "tres cuadros de arte sólido"  para el Ministerio de Desarrollo Social - hoy Ministerio de Salud y Desarrollo Social -, de Carolina Stanley. Pero el obsequio más llamativo es el que terminó en la Quinta Presidencial de Olivos, donde vive Macri con su familia, el 30 de octubre de 2018: se trata de   "una cuchilla grande"  como "cortesía" para con el mandatario , tal como reveló el periodista Sebastián Iñurrieta en su cuenta de Twitter. Muñiz fue detenido hoy cuando intentó ingresar a la casa de Gobierno con un  arma  en mano, argumentando una reunión con Mauricio Macri. LEER MÁS:  El arma que le secuestraron al hombre que quiso entrar a Casa Rosada """,
    """El columnista de  La Nación   Carlos Pagni  hizo una inesperada revelación y contó que el dueño del grupo América,  Daniel Vila , preferiría a  Cristina Kirchner  por sobre  Mauricio Macri en un evental balotaje presidencial.  El conductor de  Odisea Argentina  recordó la presencia del empresario de medios en  la presentación del libro de Cristina en la Feria  y también  la asistencia de su socio, José Luis Manzano, a la charla que dio Axel Kicillof  en los Estados Unidos la semana pasada.  Inclusive, Pagni aseveró que estos movimientos anticiparían un eventual acercamiento de  Sergio Massa  con  Cristina Kirchner de cara a las próximas elecciones.  "Vila había cenado la noche anterior (a la presentación de  Sinceramente ) con un grupo de peronistas no kirchneristas y, al pasar, adelantó que, si tuviera que elegir entre Macri y Cristina, preferiría a la expresidenta", relató Pagni en su programa de  La Nación+ .                                                                                                    """,
    """El analista político  Jorge "El Turco" Asis  afirmó que los macristas deben reconocer que les  "dejaron la cola como una regadera"  tras la aplastante derrota electoral de  Cambiemos  en la provincia de  Córdoba . "Creo que los macristas lo que tienen que hacer es reconocer que les dejaron la cola como una regadera", afirmó Asis ante la conductora   Viviana Canosa  quien se ruborizó al aire por el comentario. "Veo que tratan de interpretar como que en el fondo esto les conviene: perdieron, jugaron mal", afirmó Asís. El analista político además citó a  un "peronista filósofo" , quien decía: "perder no es grave, lo grave es la cara de boludo que te queda".                                                                                                                                                                                                                                                                                                                                                                           """,
    """La abogada de  Pedro Etchebest ,  Natalia Salvo , celebró la ratificación de  Alejo Ramos Padilla  en la causa D’Alessio:  “La confirmación de la Cámara no sorprende, pero estábamos preocupados por las presiones de  Comodoro Py ”. En diálogo con el programa  “Habrá consecuencias”  de  El Destape Radio , Salvo aseguró que “esta asociación ilícita tuvo expresiones en distintos puntos de Argentina y fuera del país, con lo que no hay un juez de otro lugar que pueda intervenir” y que “A Stornelli ya no le quedan argumentos. Se tiene que presentar. Hace más de un mes que está rebelde”. Sobre la situación de su defendido, quien se encuentra fuera del país, la letrada relató que “Etchebest está bien. Tiene bronca porque no puede volver al país, no se siente seguro. Estaba satisfecho con la confirmación de Ramos Padilla”.                                                                                                                                                                                                         """,
    """Whatsapp  instó a sus usuarios a actualizar su última versión tras reportes de que sus comunicaciones podrían ser vulnerables ante la instalación de un programa de espionaje desarrollado por la compañía NSO Group, que mantiene un vínculo comercial con el gobierno de Cambiemos. La aplicación descubrió una vulnerabilidad que permitió inyectar software espía en el teléfono de un usuario a través de la función de llamada telefónica de la aplicación. Los atacantes podrían transmitir el código malicioso al dispositivo de un objetivo llamando al usuario e infectando la llamada, ya sea que el destinatario haya contestado la llamada o no. El spyware fue desarrollado por la compañía israelí de inteligencia cibernética NSO Group, según el Financial Times, que informó por primera vez la vulnerabilidad. La empresa de espionaje fue contratada por  Mauricio Macri  cuando aprovechó la visita en septiembre 2017 del primer ministro de Isreal, Benjamín Netanyahu, para adquirir este peligroso equipamiento en materia de seguridad tecnológica en beneficio del ministerio de Seguridad de  Patricia Bullrich . Por precaución ante estas sospechas de espionaje, la compañía publicó el lunes una actualización de la aplicación, y la compañía está alentando a los usuarios a que realicen una actualización por precaución. NSO Group es una compañía israelí que afirma que vende la herramienta de forma exclusiva a los gobiernos con la condición de que solo sea utilizada para combatir a terroristas o grupos criminales y carteles de drogas. """,
    """El asesor presidencial  Alejandro Rozitcher  justificó que la Argentina esté en crisis y manifestó que no es culpa del gobierno. "Para ser una crisis se tiene mucho de nacimiento, de situación nueva", manifestó. "Sería absurdo negar que existe una situación de crisis y malestar con la economía, de todos modos yo no creo que esto tenga que ver con el Gobierno:  tiene que ver con una realidad profunda de la Argentina" , sostuvo. En una entrevista en La Nación +, el filósofo afirmó que la Argentino "no ha sabido en décadas desarrollar su potencial, que se ha entrampado en patotas, corrupción y negación de los problemas". El filósofo además justificó el sufrimiento del pueblo argentino: "es bastante natural que cuando una sociedad o una persona se hace cargo a sus cuestiones tenga que vivir momentos de gran dificultad".                                                                                                                                                                                                      """,
    """La Cámara Federal de Casación Penal resolvió este martes que  Cristina Fernández de Kirchner  sea sometida a un único juicio oral por las dos causas penales en las que está procesada vinculadas a Los Sauces y Hotesur. El máximo tribunal penal del país dispuso que el Tribunal Oral Federal 5 realice un único debate en el que, en un futuro, se sentarán al banquillo la senadora de Unidad Ciudadana, y sus hijos,  Máximo  y  Florencia , entre otros procesados, según la resolución a la que accedió Télam. La Sala I del máximo tribunal lo resolvió así ante un conflicto de competencia que se había desatado entre dos tribunales para llevar adelante el juicio oral, debido a que en las dos causas hay una similitud de procesados. La causa “Los Sauces” ya había sido elevada a juicio en octubre pasado, mientras que “Hotesur” (la firma dueña del hotel Alto Calafate) iba camino a correr la misma suerte.                                                                                                                               """,
    """La  CGT , principal central obrera del país, convocó a un  paro general  de trabajadores para el próximo 29 de mayo en contra de las políticas de ajuste de Mauricio Macri. La medida de fuerza fue anunciada en conferencia de prensa por sus dos líderes Héctor Daer y Carlos Acuña, luego de un cónclave de sus dirigentes. "En forma unánime, el Consejo Directivo convoca a una medida de acción directa que se transforma en un paro de 24 horas en fecha del 29 de este mes", apuntó Daer. Además, el sindicalista planteó que la medida se irá "consensuando" con otras organizaciones gremiales y apuntó que la medida es "en reclamo de que se modifique esta aceleración de la decadencia de la economía de nuestros compañeros y nuestros hogares". La de fin de mes será la sexta huelga de la CGT desde que Macri asumió la presidencia. En este período, la conducción de la central gremial fue muy criticada por su flexibilidad frente al Gobierno y por la falta de acciones concretas para defender a los trabajadores.                      """,
    """Este 2019 tiene aún 24 o 25 elecciones por delante (según el balotaje), tras los comicios clave de ayer en la provincia de Córdoba. El próximo compromiso es en La Pampa, el próximo domingo, cuando se enfrenten el peronismo contra el radicalismo. Salvo julio y diciembre, todos los meses tendrán comicios. Solo 3 distritos competirán en la misma fecha que en las elecciones presidenciales: Ciudad de Buenos Aires, la Provincia y Catamarca. EL FIXTURE 19/05  La Pampa 02/06  Misiones San Juan 09/06  PASO Mendoza Chubut Entre Ríos Tucumán Jujuy 16/06  Tierra del Fuego Formosa San Luis Santa Fe (22/6 Cierre de Listas) 11/08  PASO Presidente PASO Ciudad Autónoma de Buenos Aires PASO Buenos Aires PASO Catamarca Santa Cruz 29/09  Mendoza 06/10  PASO Salta 27/10  Presidente Ciudad Autónoma de Buenos Aires Buenos Aires Catamarca 10/11  Salta 24/11 ¿Balotaje?                                                                                                                                                                         """,
    """El Secretario General del Gremio de Camioneros,  Hugo Moyano , se refirió a la postura de la CGT, criticó con dureza a su cúpula y marcó una clara diferencia.  “No me reuniría con el  FMI.  Terminaríamos mal. Esa reunión es parte del circo, de decir que el FMI se reúne con los sectores gremiales", señaló y a la vez, profundizó:  "La CGT, que fue históricamente el centro de los reclamos de la sociedad, están reuniéndose con el FMI. No sé qué resultado puede tener una reunión con el FMI". Del mismo modo, en declaraciones al programa  “Habrá Consecuencias”  por  el Destape Radio ,  el dirigente habló de la eventual medida de fuerza a convocar por el Consejo Directivo de la CGT.  "No hay mucha expectativa en lo que haga la CGT . No hacen lo que necesita la gente", señaló. “El Gobierno les debe miles de millones de pesos a las obras sociales, y mucho más a los que estamos en la vereda de en frente. Pagarlo sería hacer lo que corresponde", planteó. Por otra parte, y con relación a las paritarias en el gremio de camioneros, advirtió: "Me parece que la paritaria va a andar incluso arriba del 40%. Vamos a analizarlo y a dar un número". En relación al entramado judicial y la persecución de ciertos sectores de la Justicia, Moyano afirmó; "No saben que buscar para poder acusarnos de algo para lograr el objetivo de llevarnos en cana a Pablo o a mí”. Y siguió:  “Si algo se hizo mal en Independiente el responsable soy yo, no Pablo.  Que me lleven en cana a mí". Asimismo, comparó el accionar del Ejecutivo con la dictadura militar: “ Antes te mataban o te metían en cana. Hoy, con parte de la Justicia, te persiguen.  No tienen la desaparición de personas, pero actúan de la misma forma". Asimismo, el líder sindical se metió en la interna política de cara a las elecciones e hizo un repaso de su vínculo con  Cristina Kirchner . “Cuando estuve distanciado de Cristina era porque yo creía que no correspondían unos temas económicos. Pero hoy la experiencia nos da otros conocimientos", aseguró.  Y continuó: “El acercamiento a Cristina es a la política. Por supuesto también a la persona, porque nadie puede dudar de su capacidad". Sobre su antiguo víncilo con Macri, apuntó: "No me arrepiento de las cosas porque las hago por convicción. Cuando me saqué la foto con Macri fue por el monumento a Perón". En la misma línea, Moyano aseguró que “si uno toma el tiempo que gobernó Kirchner y Cristina uno no tiene dudas de que el hambre y la pobreza de hoy la gente no lo sufría". A la vez, auguró que “mi postura es que haya una gran PASO en el peronismo” y que “Cristina tiene muchas posibilidades". A futuro, el dirigente camionero no descartó la presencia de un integrante del movimiento obrero en los primeros planos  de la política nacional. “Veo muchos jóvenes obreros que pintan bien para tener un hombre del movimiento obrero en la Presidencia", aseguró, Y completó: “El hombre del movimiento obrero que llegue a la Presidencia va a hacer los imposible para que a ningún niño le falte un plato de comida, porque lo hemos vivido". """,
    """La ex presidenta  Cristina Fernández de Kirchner  participó de una reunión de la mesa directiva y la Comisión de Acción Política (CAP) partidarias del  Partido Justicialista , en la sede de Matheu, y dejó ciertas definiciones para las elecciones del 27 de octubre. La senadora de Unidad Ciudadana  "se puso a disposición para construir una coalición grande en el lugar que sea" , tal como pudo saber  El Destape . Las candidaturas recién se conocerán el próximo 22 de junio. Según trascendió del hermético encuentro,  Cristina Kirchner habló durante 20 minutos  en soledad. En ese lapso  repasó las políticas y crisis económica provocadas por el macrismo , como la histórica y abultada deuda contraída. "No se habló de nadie en particular" , respondieron ante la consulta de  El Destape  si  Sergio Massa  fue un tema de conversación en la reunión. Cristina Kirchner advirtió sobre las problemáticas que afrontará el próximo gobierno por las consecuencias del modelo económico. En relación a eso, fuentes del Instituto Patria que dialogaron con este portal, marcaron: "La alianza que gobierne después del 10 de diciembre, necesariamente tendrá que ser más amplia que la alianza electoral por la magnitud de los problemas económicos que deja Cambiemos". Entre ellos, cuentan que Cristina apuntó a la deuda externa, la destrucción de mercado interno y el desempleo. En esa línea, la ex Presidenta abordó temáticas complejas como la destrucción de la economía, la destrucción del mercado interno y del poder adquisitivo. LEER MÁS:  La foto de Cristina Kirchner con la mesa de acción política del PJ Sindicalistas como  Hugo Moyano ,  Hugo Yasky, Ricardo  Pignanelli y  Omar Plaini  e intendentes como  Verónica Magario  (La Matanza),  Fernando Gray  (Esteban Echeverría),  Gustavo Menéndez  (Merlo) y  Leonardo Nardini  (Malvinas Argentinas) estuvieron presentes. También, la mesa de acción política está conformada por  Alberto Fernández ,  Rubén Marín ,  Beatriz Rojkes ,  Alberto Rodríguez Saá  (no estuvo),  Ginés González García ,  Fernando 'Chino' Navarro ,  Jorge Landau ,  María Emilia Soria ,  Cristina Álvarez Rodríguez  y  Fernando Espinoza . """,
    """Luego de la de participar de la cumbre del PJ junto con  Cristina Kirchner , el diputado  Daniel Scioli  dio detalles de la reunión y apuntó hacia la unidad de la oposición. "El denominador común pasa por la gravedad del ajuste, cómo está golpeando en las pymes, los trabajadores y los jubilados", afirmó Scioli en declaraciones a la prensa frente a la sede del partido. Scioli es uno de los dirigentes que ya anunció su intención de ser precandidato a presidente, como los también presentes Agustín Rossi y Felipe Solá, resaltó "la necesidad de hacer un gran frente no solamente en lo electoral sino luego más amplio aún para gobernar". Sobre la reunión, el ex vicepresidente señaló que se dio en términos normales. "Gioja hizo una introducción, luego habló Cristina y dio su punto de vista sobre esta realidad", detalló.                                                                                                                                                                                                           """,
    """El presidente del Partido Justicialista a nivel nacional,  José Luis Gioja , dio una conferencia de prensa tras la reunión con  Cristina Kirchner  en la sede central del PJ, en la calle porteña de Matheu. "Nunca dudamos del peronismo de Cristina" , afirmó el presidente del partido tras la cumbre del peronismo con la ex Presidenta. Cristina Kirchner asistió a la Mesa de Acción Política del Consejo Nacional del PJ. Gioja contó detalles del encuentro y reveló que antes de mayo se lanzará un "frente patriótico" opositor. "Ella quería venir a conversar con los compañeros del Justicialismo. Nunca dudamos ni de su peronismo ni de su capacidad de ser oposición y ser  hoy la primera referenta de la política argentina como creemos que lo es" , afirmó Gioja. Relató que estuvieron reunidos con Cristina 50 minutos y ella dio "un panorama más que interesante, reiteró algunos conceptos que ya habíamos escuchado en la presentación del libro Sinceramente", contó el mandatario partidario. "Definimos con ella que este partido va a ser el frente patriótico que tenemos que hacer. Hay que hacerlo antes de que finalice el mes de mayo . Ahí estaremos en condiciones de hacer el frente", confirmó. Y siguió elogiando a la senadora de Unidad Ciudadana. "La vimos muy estadista, no dejó tema de actualidad por tocar. Lo más importante es la coincidencia que hemos tenido del análisis que hace de la realidad argentina". Para finalizar, Gioja contó que Cristina reiteró que "no va a ser la ultima vez que venga". Sobre las ausencias de algunos peronistas, Gioja manifestó: "Fuimos hilando finito y convocando a todos los compañeros, reiteramos la invitación a todos los compañeros.  Creemos que hay un montón de compañeros que no están en esta estructura formal y que piensan lo mismo y reiteramos el llamado para que estén".  """,
    """Por segunda vez en dos días, el anexo de la cámara de Diputados debió ser desalojado por una amenaza de bomba.  En el lugar trabaja la brigada de explosivos de la Policía Federal. Más temprano se registraron dos amenazas de este estilo, una en el canal Telefe y otra en el Hospital Santojani. Ayer pasó lo mismo en el anexo de Diputados y en la Casa Rosada. LEER MÁS:  Amenaza de bomba en Casa Rosada y el anexo de Diputados                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         """,
    """La diputada  Elisa Carrió  estalló con la alianza Cambiemos con una serie de audios, al que llama que "son un asco". Contundentes definiciones contra sus socios, tras la derrota de Mario Negri en Córdoba. "Qué terrible es que en las derrotas se borren todos. Me dan asco", lanzó.  Tensión en Cambiemos por la caída del radical, quien quedó a 40 puntos del reelecto peronista Juan Schiaretti. LOS AUDIOS ESCANDALOSOS Para Lilita, hubo traición, abandono e indiferencia  para con el candidato radical al que ella apoyó públicamente y generó caos en su provincia. "¿Qué van a hacer si nos derrotan? ¿Se van a borrar? Yo no estoy para borrarme. Pero si esa es la política, sí estoy dispuesta a no estar", lanzó en una serie de escuchas que publicó hoy en sus redes sociales oficiales. Con tono durísimo, tiró Carrió: "Que el Gobierno nacional no se siente prescindente, porque los dirigentes de  Cambiemos  que pelean en las provincias también tienen que defender a un Gobierno que no puede obtener resultados económicos". Además, le pegó a un ministro de Mauricio Macri. "Cambiemos no acompañó a Cambiemos.  El ministro del Interior siempre hizo su sociedad con los gobernadores del PJ". Hablaba de Rogelio Frigerio . "La vida no es compartir el éxito y alejarse en la derrota. Me parece inhumano. Tenemos que reflexionar sobre cuánto le debemos a Mario Negri, cuánto tuvo que bancarse la indiferencia, la superficialidad, la falta de escucha. Falta de estrategia de Cambiemos nacional, que es una constante", cerró. """,
    """El  Sindicato de Empleados de Comercio  avanza en una negociación paritaria con las cámaras empresarias. Según pudo saber  El Destape , el objetivo es  conseguir un 30% de aumento  mediante una  recomposición salarial del 5% bimensual , pero aún el acuerdo no fue firmado y se resolverá en los próximos días. El acuerdo que se dividirá en segmentos de alrededor del 5% cada dos meses hasta abril de 2020 , según informó Clarín. Sin embargo, este medio pudo saber que la Federación Argentina de Empleados de Comercio y Servicios aún no confirmó si ese será el porcentaje a recomponer o si será mas y siguen las negociaciones. Además, la Confederación Argentina de la Mediana Empresa tampoco se pronunció al respecto y lo haría en los próximos días. De concretarse, la firma de la paritaria del sindicato que conduce  Armando Cavalieri  se convertiría en una referencia para el resto de las entidades de trabajadores, ya que posee gran peso en el mapa gremial debido al millón de afiliados que posee en el país. Desde el entorno de la CAME advirtieron que aun no fue homologado el acuerdo. Ante esto, la FAECYS señalaron que "va a ser así" y que "tecnicismos" son los que frenan la firma. """,
    """Diputados nacionales del FPV-PJ presentaron un proyecto para  impulsar el juicio político contra el ministro de Justicia y Derechos Humanos de la Nación, Germán Garavano,  por mal desempeño y eventuales delitos en el ejercicio de sus funciones. El pedido de juicio político está encabezado por los diputados  Rodolfo Tailhade, Agustín Rossi y Leopoldo Moreau  y se basa en “las presiones indebidas dirigidas a forzar la renuncia del  Dr. Carlos Rozanski  a su cargo de juez federal” y a “la negociación con el arrepentido  Leonardo Fariña  para garantizar el contenido de sus declaraciones en sede judicial” y direccionarlas en contra de la ex presidenta  Cristina Fernández de Kirchner. Tal como declaró Moreau esta mañana en Radio Cooperativa,  “quedó plasmado que (Garavano) ofrecía beneficios a delincuentes a cambio de que fraguaran declaraciones en expedientes contra Cristina Kirchner”.  El diputado explicó que hay "evidencias y grabaciones” que sitúan al funcionario en una reunión Fariña. Según fundamentaron los impulsores del proyecto, ésto comenzó el 29 de marzo de 2016 cuando Fariña recibió el primer mail indicándole qué debía declarar en sede judicial. En el orden cronológico, el próximo episodio ocurrió el 28 de abril, cuando el Consejo de la Magistratura votó la vuelta a comisión del expediente 54/13 contra Rozanski, por más que ya se hubiera vencido el plazo para tratarlo. LEER MÁS:  El audio de la extorsión de Garavano y Cabral a Rozanski “Por esto es que el 28 de junio, cuando se dio la  reunión entre Garavano, Fariña y (la abogada Giselle) Robles , el ministro les garantizó -entre otras cuestiones- que el Dr. Rozanski sería desplazado de su cargo”, afirmaron los diputados. Este hecho tuvo lugar el 20 de junio, un día después de que Rozanski se reuniera con Garavano y con el consejero de la Magistratura Luis María Cabral, quienes, como reveló El Destape, lo presionaron para renunciar. "Con la maniobra cerrada,  ni Fariña ni el Gobierno tendrían que volver a preocuparse por la intervención de un juez que no les servía  para la pata judicial de su aparato de persecución", argumentaron. Según la hipótesis de los legisladores del FPV-PJ, a través de su intervención personal Garavano logró dos cosas:  “Consiguió presionar a un juez federal para que presentara su renuncia  y así no interviniera en ninguna causa vinculada a un arrepentido en particular" por un lado y, por otro,  "que ese arrepentido siguiera declarando en otra causa judicial en la misma línea que lo venía haciendo , lo que implicaba seguir repitiendo lo que le llegaba en correos anónimos para así poder implicar a la ex presidenta Cristina Fernández de Kirchner”. """,
    """Se acercan las elecciones presidenciales y el primer debate tiene su fecha y lugar a realizarse y la decisión radicó que la sede será la Universidad Nacional del Litoral, en Santa Fe, el 13 de octubre.  Una semana después tendrá lugar en la Ciudad de Buenos Aires. El debate se hará después de las elecciones Primarias Abiertas Simultáneas y Obligatorias (PASO), con lo cual estarán los candidatos que hayan logrado atravesar esa instancia. El cierre de listas es el 22 de junio y las PASO se realizarán el 11 de agosto. Según confirmó el intendente de Santa Fe, José Corral, será en el Paraninfo, un espacio de la Universidad del Litoral, en la capital de Santa Fe. Es el mismo predio en donde se reunió la asamblea de constituyentes que modificaron la Constitución en 1994. En 2015 hubo un debate entre Macri y Scioli, pero esta será la primera vez que se realice a partir de la ley que establece la obligatoriedad de los debates presidenciales. Es la ley 27.337, sancionada en noviembre de 2016.   """,
    """El Secretario General de la Fraternidad,   Omar Maturano ,  confirmó que los gremios de transporte  convocarán a un paro en la última semana de mayo o la primera de junio  y advirtió que el resto de  la  CGT  tiene voluntad de plegarse a la medida  en la reunión de Consejo Directivo que se realizará esta tarde: “De parte del transporte vamos a hacer un paro la última semana de mayo o la primera de junio", señaló. A la vez que confirmó que  “hay voluntad” en el resto de los dirigentes de la cúpula porque “las condiciones para un paro están a la orden del día”. En diálogo con el programa  “Navarro 2019”  por  el Destape Radio ,  el gremialista dio detalles de la reunión de ayer  entre la CGT y el FMI y advirtió que “el FMI nos dijo que la inflación va a bajar en el segundo semestre"  y que “el FMI nos dijo que van a ayudar a este gobierno o el que venga". Además, aclaró: “En el FMI nos dijeron que ya le dieron al gobierno 90% del préstamo, quedan apenas 5.000 M de USD para el 2020, cuando vamos a tener que empezar a pagarlo”. Por otra parte y en torno al panorama político, Maturano afirmó: “"Estamos más cerca de Lavagna. Creemos que él va a ser el candidato del peronismo", indicó que “nos llevamos mal con Cristina, nos cobraba impuesto a las ganancias" y advirtió que “si Cristina se baja, podemos unirnos todos”. """
    ]
    
    
if __name__=="__main__":
    #text_file = open("texto.txt","r")
    #text = text_file.read()
    table = str.maketrans(dict.fromkeys(string.punctuation))  # OR {key: None for key in string.punctuation}
        
    for text in my_text:
        text = text.lower()
        text_clean = text.translate(table)   
        
        entities = []
        for entity in ENTITIES:
            entity = entity.lower()
            found = [e for e in findall(entity,text_clean)]
            if len(found) > 0:
                entities.append((entity, found))

        quotes_re = re.compile('[\"“]([^\"”]*)?[\n\"”]\s*(?:[\.\s,]|$)') #non greedy regex to find new quotes and stop at newlines
        quotes = [(q,text.find(q)) for q in re.findall(quotes_re,text)]
        
        verbs = []
        for verb in VERBS:
            found = [e for e in findall(verb,text_clean)]
            if len(found) > 0:
                verbs.append((verb,found))

        entities_found = []
        for verb in verbs:
            for verb_pos in verb[1]:
                for entity in entities:
                    for entity_pos in entity[1]:
                        if abs(verb_pos-entity_pos) < len(verb[0]) + len(entity[0]) + 10:
                            entities_found.append((entity[0], entity_pos))

        if(len(entities_found) > 0):
            print(text, "\n", entities_found)


